### PR TITLE
Update to SO 16.04

### PR DESCRIPTION
**Pull request by breed808**
Update script to handle latest SecurityOnion version (16.04).

Readme uses current project name (so1404-ntopng-installer), it might be worth changing the project name to reflect the updated version.

### CODE REVIEW

**Review by branchnetconsulting — COMMENTED** [review]
Ben, thanks for your contribution!  I do not have an SO system running 16.04 at the moment so please tell me about how your testing went after you used the adapted script to install ntopng.  I assume ntopng comes up OK in a browser, but did you also confirm that PF_RING is working for ntopng?  You should see a PF_RING status file for ntopng (find it with "grep ntop /proc/net/pf_ring/*") and in that file the value for "Tot Read" should be growing.  Is it?

**Comment by breed808** [comment]
Hi Kevin,

NtopNG is appearing OK in the browser, and showing the expected traffic numbers:
```
breedy@sensor-bre ~> grep ntop /proc/net/pf_ring/*
/proc/net/pf_ring/28334-eno1.1409:Appl. Name         : ntopng

breedy@sensor-bre /p/1/n/pf_ring> grep Tot /proc/net/pf_ring/28334-eno1.1409 
Tot Memory         : 7057408
Tot Packets        : 141254450
Tot Pkt Lost       : 0
Tot Insert         : 141254450
Tot Read           : 141254448
```

The `Tot Read` counter is incrementing, as are the other `Tot` entries.

**Comment by branchnetconsulting** [comment]
Yes, I like the idea of renaming the repo from **so1404-ntopng-installer** to **so-ntopng-installer**.  I will want to make sure the repo provides a solution for installing the latest stable ntopng onto SO for both Ubuntu 16.04 and 14.04.  I presume I should split the repo into a 16.04 and 14.04 branch and then reference both a 16.04 and 14.04 version of the download link for the script in the README.  Or maybe we should just have two different installer scripts in the master branch: install_ntopng_on_so_14 and install_ntopng_on_so_16.  That might be simpler.  I will likely move in that direction in the next day or so, as I am a bit backed up at the moment. 

In the mean time would you please resubmit your new version of **install_ntopng_on_so** as **install_ntopng_on_so_16** ?

Thanks!
Kevin

**Comment by breed808** [comment]
Of course, I'll rebase the commit to copy the file with the changes.
Changes have been made, see the current commit in the merge request.

**Pull request merged**
